### PR TITLE
abaplint bin command fix

### PR DESCRIPTION
**Pull request by sbcgua**
to #297

### CODE REVIEW

**Comment by larshp** [comment]
hmm, I changed it a while back, so that it is possible to add `--experimental-worker` in the executeable

**Comment by sbcgua** [comment]
I see ...

Well, in my machine this works (abaplint file) - of course should be tested in the environment you want it to work ...

```
#!/usr/bin/env node --experimental-worker

const worker = require('worker_threads'); <<< TO CONFIRM FLAG IS ACTIVE

require("./build/src/cli");
```

Option 2: separate bin for experimental run e.g. `abaplint-beta` or `abaplint-with-node-params`

or .... ? just to ignore this issue

**Comment by larshp** [comment]
doesnt seem to work, running on windows,

image

**Comment by sbcgua** [comment]
Hmmm ... OK ... it is a bit controversial  at least at my level of shell knowledge.

the file above works if installed as package e.g.
```sh
npm link (or real npm install)
abaplint -h
```
If I understand correctly this is because npm actually wraps the script in a shell script which ignores shebang stuff in the file itself and ACCEPTS params
```sh
npm link
which abaplint
cat ... ^^^

#!/bin/sh                                                                              
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")                                  
                                                                                       
case `uname` in                                                                        
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;                                        
esac                                                                                   
                                                                                       
if [ -x "$basedir/node" ]; then                                                        
  "$basedir/node"  --experimental-worker "$basedir/node_modules/abaplint/abaplint" "$@"
  ret=$?                                                                               
else                                                                                   
  node  --experimental-worker "$basedir/node_modules/abaplint/abaplint" "$@"           
  ret=$?                                                                               
fi                                                                                     
exit $ret                                                                              

```

running `./xxxx --param` does not work indeed. However there is a param -S which allows this.

```
#!/usr/bin/env -S node --experimental-worker
```

Then I can run from dev dir directy
```
./abaplint -h
```

BUT this stops working with npm !!!

Imho to summarize: to add additional script with `-S`. If this is used for developer experiments then it should be just fine and for npm scripts use the one without additional params. (see last commit)

**Comment by larshp** [comment]
also does not seem to work,
image

**Comment by sbcgua** [comment]
Hmmmmm, will have a look

**Comment by sbcgua** [comment]
OK, here is a new approach. Seems like `-S` is not available in all environments. Also I checked my older js projects how I did there and this is it. So the key fact is that shebang seems to be non universal.

1. abaplint renamed to abaplint.js (this is JS file isn't it ?)
2. bin in package.json refers to abaplint.js
3. js file keeps shebang. Seems like npm installs it differently in case of with and without shebang.
4. The above ensures `npm` related scenarion work (npm link, npm install), so AG scenario will also work (as it uses npm install)
5. Checked `npm link` + `abaplint -h` in irrelevant dir: works both for bash and cmd
6. added abaplint, 755, shell script, runs `node abaplint.js`. To run in dev env. `./abaplint -h` works
7. added abaplint.bat, cmd script, runs `node abaplint.js`. To run in dev env on win on cmd. 'abaplint -h' at dev dir works

**Comment by larshp** [comment]
1: IMHO, no, it starts with `#!/usr/bin/env node` which is not JavaScript

**Comment by sbcgua** [comment]
1: but it calls `require` :) Anyway the point was to make `abaplint` (the file w/o extension) a shell script and not a js file. We can keep `abaplint` name, just remove shebang from it and rename shell script to `abaplint.sh`

The final goal imho is:
- abaplint works after npm install (invoked by "user")
- abaplint can be called from dev dir for experiment with parameters (which is achieved by dedicated shell scripts for win/unix) (invoked by "developer")

And the problem is that it seems that it is not possible to do with one single file for all environments (at least from what I understand)

**Comment by larshp** [comment]
any tips for reproducing the issue? see original issue

**Comment by larshp** [comment]
what is the minimal solution to get it running, while ignoring the worker threads issue? Could just force users wanting to use the worker threads to do manual commands

**Comment by sbcgua** [comment]
ok. attempt number 3 :) Have a look. (don't merge if OK, there a debug log output)

```
$ ./abaplint -h
worker_threads NOT found
Usage: abaplint [options] [file ...]
...
$ ./abaplint-x -h                   
worker_threads found!               
Usage: abaplint [options] [file ...]
...
```
after `npm link`
bash
image
cmd
image

**Comment by larshp** [comment]
this looks good 👍 

the spawn and abaplint-x will work until/if worker threads are enabled by default

if you remove the debug output, then I'll merge it

**Comment by sbcgua** [comment]
done
:tada: :smile:

**Comment by larshp** [comment]
will release a new version tomorrow, if I remember it

**Comment by larshp** [comment]
1.5.2 published, try again

**Comment by sbcgua** [comment]
Works now :tada: 
image

**Pull request merged**
